// <auto-generated />
using System;
using BusinessObject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("PK__activity__9E2397E0D2B13D2D");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.AiAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("analysis_type");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("PK__ai_analy__3214EC0789A501F9");

                    b.HasIndex("TaskId");

                    b.ToTable("ai_analysis", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.AiRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("RecommendationType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("assign")
                        .HasColumnName("recommendation_type");

                    b.Property<double?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<int?>("SuggestedUserId")
                        .HasColumnType("int")
                        .HasColumnName("suggested_user_id");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("PK__ai_recom__3213E83F21EB708F");

                    b.HasIndex("SuggestedUserId");

                    b.HasIndex("TaskId");

                    b.ToTable("ai_recommendations", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evaluation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<int?>("CommunicationScore")
                        .HasColumnType("int")
                        .HasColumnName("communication_score");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DeadlineScore")
                        .HasColumnType("int")
                        .HasColumnName("deadline_score");

                    b.Property<int?>("LeaderId")
                        .HasColumnType("int")
                        .HasColumnName("leader_id");

                    b.Property<int?>("SkillScore")
                        .HasColumnType("int")
                        .HasColumnName("skill_score");

                    b.Property<int?>("TeamworkScore")
                        .HasColumnType("int")
                        .HasColumnName("teamwork_score");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EvaluationId")
                        .HasName("PK__evaluati__827C592D8C87BA03");

                    b.HasIndex("LeaderId");

                    b.HasIndex("UserId");

                    b.ToTable("evaluations", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.Invitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invitation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("InvitationId")
                        .HasName("PK__invitati__94B74D7CA75E2E4F");

                    b.HasIndex("TeamId");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("ProjectId")
                        .HasName("PK__projects__BC799E1FAD18A4D5");

                    b.HasIndex("TeamId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("skill_name");

                    b.HasKey("SkillId")
                        .HasName("PK__skills__FBBA83797F619518");

                    b.HasIndex(new[] { "SkillName" }, "UQ__skills__73C038ADD9DB64DB")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("AiSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ai_summary");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int")
                        .HasColumnName("difficulty");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("int")
                        .HasColumnName("estimated_time");

                    b.Property<string>("Priority")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("priority");

                    b.Property<int?>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("risk_level");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("TaskId")
                        .HasName("PK__tasks__0492148DFA0DD50E");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectId");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasTrigger("trg_task_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("BusinessObject.Models.TaskAssignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__task_ass__3213E83FEEB4DF50");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TaskId", "UserId" }, "UQ__task_ass__EF09F7FCF68B3887")
                        .IsUnique()
                        .HasFilter("[task_id] IS NOT NULL AND [user_id] IS NOT NULL");

                    b.ToTable("task_assignees", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.TaskComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("PK__task_com__E7957687818A02F9");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.TaskEmbedding", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Embedding")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("embedding");

                    b.HasKey("TaskId")
                        .HasName("PK__task_emb__0492148D47BA0192");

                    b.ToTable("task_embeddings", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.TaskLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int?>("Progress")
                        .HasColumnType("int")
                        .HasColumnName("progress");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.HasKey("LogId")
                        .HasName("PK__task_log__9E2397E02B7D9E0A");

                    b.HasIndex("TaskId");

                    b.ToTable("task_logs", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.TaskRequiredSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskRequiredSkill");
                });

            modelBuilder.Entity("BusinessObject.Models.TaskVersion", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("version_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int?>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("VersionId")
                        .HasName("PK__task_ver__07A58869AABF27E6");

                    b.HasIndex("TaskId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("task_versions", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("TeamId")
                        .HasName("PK__teams__F82DEDBC30602299");

                    b.HasIndex("CreatedBy");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__team_mem__3213E83F1EBDEBBB");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TeamId", "UserId" }, "UQ__team_mem__13B60ECD231DA964")
                        .IsUnique()
                        .HasFilter("[team_id] IS NOT NULL AND [user_id] IS NOT NULL");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("MEMBER")
                        .HasColumnName("role");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370FDD62F7C2");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E61644BB714A5")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasTrigger("trg_user_status");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("BusinessObject.Models.UserAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailableHours")
                        .HasColumnType("int")
                        .HasColumnName("available_hours");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__user_ava__3213E83FB13E13B5");

                    b.HasIndex("UserId");

                    b.ToTable("user_availability", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__user_ski__3213E83FFDF7CCA2");

                    b.HasIndex("SkillId");

                    b.HasIndex(new[] { "UserId", "SkillId" }, "UQ__user_ski__36059F39A964580F")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL AND [skill_id] IS NOT NULL");

                    b.ToTable("user_skills", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.AiAnalysis", b =>
                {
                    b.HasOne("BusinessObject.Models.Task", "Task")
                        .WithMany("AiAnalyses")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ai_analysis_tasks");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BusinessObject.Models.AiRecommendation", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "SuggestedUser")
                        .WithMany("AiRecommendations")
                        .HasForeignKey("SuggestedUserId")
                        .HasConstraintName("FK__ai_recomm__sugge__04E4BC85");

                    b.HasOne("BusinessObject.Models.Task", "Task")
                        .WithMany("AiRecommendations")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__ai_recomm__task___03F0984C");

                    b.Navigation("SuggestedUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BusinessObject.Models.Evaluation", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "Leader")
                        .WithMany("EvaluationLeaders")
                        .HasForeignKey("LeaderId")
                        .HasConstraintName("FK__evaluatio__leade__5FB337D6");

                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithMany("EvaluationUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__evaluatio__user___5EBF139D");

                    b.Navigation("Leader");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.Invitation", b =>
                {
                    b.HasOne("BusinessObject.Models.Team", "Team")
                        .WithMany("Invitations")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__invitatio__team___6B24EA82");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BusinessObject.Models.Project", b =>
                {
                    b.HasOne("BusinessObject.Models.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__projects__team_i__6E01572D");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BusinessObject.Models.Task", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "CreatedByNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__tasks__created_b__71D1E811");

                    b.HasOne("BusinessObject.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__tasks__project_i__70DDC3D8");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BusinessObject.Models.TaskAssignee", b =>
                {
                    b.HasOne("BusinessObject.Models.Task", "Task")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__task_assi__task___7C4F7684");

                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__task_assi__user___7D439ABD");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.TaskComment", b =>
                {
                    b.HasOne("BusinessObject.Models.Task", "Task")
                        .WithMany("TaskComments")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__task_comm__task___00200768");

                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithMany("TaskComments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__task_comm__user___01142BA1");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.TaskEmbedding", b =>
                {
                    b.HasOne("BusinessObject.Models.Task", "Task")
                        .WithOne("TaskEmbedding")
                        .HasForeignKey("BusinessObject.Models.TaskEmbedding", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_task_embeddings_tasks");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BusinessObject.Models.TaskLog", b =>
                {
                    b.HasOne("BusinessObject.Models.Task", "Task")
                        .WithMany("TaskLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_task_logs_tasks");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BusinessObject.Models.TaskRequiredSkill", b =>
                {
                    b.HasOne("BusinessObject.Models.Skill", "Skill")
                        .WithMany("TaskRequiredSkills")
                        .HasForeignKey("SkillId");

                    b.HasOne("BusinessObject.Models.Task", "Task")
                        .WithMany("TaskRequiredSkills")
                        .HasForeignKey("TaskId");

                    b.Navigation("Skill");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BusinessObject.Models.TaskVersion", b =>
                {
                    b.HasOne("BusinessObject.Models.Task", "Task")
                        .WithMany("TaskVersions")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__task_vers__task___76969D2E");

                    b.HasOne("BusinessObject.Models.User", "UpdatedByNavigation")
                        .WithMany("TaskVersions")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__task_vers__updat__778AC167");

                    b.Navigation("Task");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("BusinessObject.Models.Team", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "CreatedByNavigation")
                        .WithMany("Teams")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__teams__created_b__6383C8BA");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("BusinessObject.Models.TeamMember", b =>
                {
                    b.HasOne("BusinessObject.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__team_memb__team___6754599E");

                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__team_memb__user___68487DD7");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.UserAvailability", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithMany("UserAvailabilities")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__user_avai__user___5BE2A6F2");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.UserSkill", b =>
                {
                    b.HasOne("BusinessObject.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .HasConstraintName("FK__user_skil__skill__5812160E");

                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__user_skil__user___571DF1D5");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BusinessObject.Models.Skill", b =>
                {
                    b.Navigation("TaskRequiredSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("BusinessObject.Models.Task", b =>
                {
                    b.Navigation("AiAnalyses");

                    b.Navigation("AiRecommendations");

                    b.Navigation("TaskAssignees");

                    b.Navigation("TaskComments");

                    b.Navigation("TaskEmbedding");

                    b.Navigation("TaskLogs");

                    b.Navigation("TaskRequiredSkills");

                    b.Navigation("TaskVersions");
                });

            modelBuilder.Entity("BusinessObject.Models.Team", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Projects");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("BusinessObject.Models.User", b =>
                {
                    b.Navigation("AiRecommendations");

                    b.Navigation("EvaluationLeaders");

                    b.Navigation("EvaluationUsers");

                    b.Navigation("TaskAssignees");

                    b.Navigation("TaskComments");

                    b.Navigation("TaskVersions");

                    b.Navigation("Tasks");

                    b.Navigation("TeamMembers");

                    b.Navigation("Teams");

                    b.Navigation("UserAvailabilities");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
